<div id="help_page">
    <div id = "page_title">Personal Monitoring System</div>
    
    <?php $this->placeholder('left_sidebar')->captureStart() ?>
		<h4>Navigation</h4>
		<ul>
		    <li><a href = "/">
		        Home</a></li>
		    <li><a href = "/add-user/sign">
		        Add user</a></li>
		    <li>
		        Help</li>
		    <li><a href="/my-account">
		        My Account</a></li>
		    <li><a href="/index/logout">
		        Logout</a></li>
		</ul>
	<?php $this->placeholder('left_sidebar')->captureEnd() ?>
    
    
    
    <?php echo $this->placeholder('left_sidebar'); ?>   
    
 	<div id = "central_text">
 		Here is a help page! And this the first change!<br />
 		nest line
 	</div>
     
    
</div>
